import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ["latin"] });
import "react-datepicker/dist/react-datepicker.css"; 

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import NavbarHome from "@/components/Navbar";

export const metadata = {
  title: "FYP",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div>
            <NavbarHome/>
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}